announproject/urls.py

from django.contrib import admin
from announ import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from user_profile import prof_views
from chat import chat_views

from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.main, name='home'),
    path('SRAST/', views.SRAST, name='SRAST'),
    path('SRAST/createannoun/',views.announcreate,name='announcreate'),
    path('SRAST/announs/id=<int:id>',views.announshow,name='announshow'),
    path('SRAST/announs/', views.allannoun, name='announlist'),
    path('SRAST/profile/', prof_views.user_profile, name='user_profile'),
     path('SRAST/profile/change', prof_views.change_profile, name='changeprofile'),
    path('SRAST/category/<int:category_id>/', views.category_detail, name='category'),
    path('SRAST/announs/id=<int:id>/profile',prof_views.owner_profile,name='owner_profile'),
    path('accounts/', include('registration.urls')),
     path('SRAST/inbox/', chat_views.inbox, name="inbox"),
    path('SRAST/message/<str:pk>/', chat_views.viewMessage, name="message"),
    path('SRAST/create-message/<int:user_id>/', chat_views.createMessage, name="create-message"),
   # path('', TemplateView.as_view(template_name="index.html"), name='home'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_profile/models.py
from django.db import models

# Create your models here.

user_profile/forms.py
from django import forms

class ProfileForm(forms.Form):
     name = forms.CharField(initial='Твоё имя', max_length=30, required=False)
     surname = forms.CharField(initial='Твоя фамилия', max_length=30, required=False)
     bio = forms.CharField(max_length=500)
     location = forms.CharField(initial='Напиши город/село/деревню, где ты живёшь', max_length=30, required=False)
     birth_date = forms.DateField(required=False)
     img = forms.ImageField(required=False)

user_profile/templates/user_profile/owner_profile.html
{% extends "base.html" %}
{% block optional_link %}
{% endblock %}
{% load static %}
{% block content %}
<head>
    <meta charset="UTF-8">
    <title>Профиль пользователя</title>
    {% block style %}
    <link rel="stylesheet" href="{% static 'user_profile/css/user_proffile.css' %}" >
    {% endblock style %}
</head>
<body>
    <div1>
    <div class="profile">
        <h2>Профиль пользователя</h2>
        <img src="{{ about_user.img.url }}" alt="{{ announ.name }}" class="owner_profile-image">
        <p><strong>Имя:</strong> {{ about_user.name }}</p>
        <p><strong>Фамилия:</strong> {{ about_user.surname }}</p>
        <p><strong>Email:</strong> {{ about_user.user.email }}</p>
        <p><strong>Немного обо мне:</strong> {{ about_user.bio }}</p>
        <!-- Добавьте дополнительные поля здесь, если необходимо -->
    </div>
</div1>
    <div2>
        <div class="user-ads">
            <h3>Объявления пользователя</h3>
            {% for announ in announs %}
            <div class="announ-container">
                <img src="{{ announ.img.url }}" alt="Фото объявления" class="announ-image">
                <div class="announ-details">
                    <!-- Добавляем подпись к названию -->
                    <h2><a href="{% url 'announshow' announ.id_announ %}">{{ announ.name }}</a></h2>
                    <p>Стоимость: <span class="announ-value">{{ announ.value }}</span> руб.</p>
                    <p>Категория: <span class="announ-cat">{{ announ.announ_cat }}</span></p>
                    <!-- Добавляем подпись к изображению -->
                    <p class="announ-description">{{ announ.description }}</p>
                </div>
            </div>
            {% endfor %}
        </div>
    </div2></body>
</html>
{% endblock content %}

user_profile/templates/user_profile/profile_change.html
{% extends "base.html" %}
{% block optional_link %}
{% endblock %}
{% load static %}
{% block content %}
<head>
    <meta charset="UTF-8">
    <title>Редактирование профиля</title>
    {% block style %}
    <link rel="stylesheet" href="{% static 'user_profile/css/profile_change.css' %}" >
    {% endblock style %}
</head>
<body>
    <div class="profile">
        <h2>Редактирование профиля</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_name">Имя:</label>
                <input type="text" name="name" id="id_name" value="{{ about_user.name }}" maxlength="30">
            </div>
            <div class="form-group">
                <label for="id_surname">Фамилия:</label>
                <input type="text" name="surname" id="id_surname" value="{{ about_user.surname }}" maxlength="30">
            </div>
            <div class="form-group">
                <label for="id_bio">Немного обо мне:</label>
                <textarea name="bio" id="id_bio">{{ about_user.bio }}</textarea>
            </div>
            <div class="form-group">
                <label for="id_location">Адрес:</label>
                <input type="text" name="location" id="id_location" value="{{ about_user.location }}" maxlength="30">
            </div>
            <div class="form-group">
                <label for="id_birth_date">Дата рождения:</label>
                <input type="date" name="birth_date" id="id_birth_date" value="{{ about_user.birth_date|date:'Y-m-d' }}">
            </div>
            <div class="form-group">
                <label for="id_img">Фотография:</label>
                <input type="file" name="img" id="id_img">
            </div>
            <button type="submit">Сохранить изменения</button>
        </form>
    </div>
</body>
</html>
{% endblock content %}

user_profile/templates/user_profile/user_profile.html
{% extends "base.html" %}
{% block optional_link %}
{% endblock %}
{% load static %}
{% block content %}
<head>
    <meta charset="UTF-8">
    <title>Профиль пользователя</title>
    {% block style %}
    <link rel="stylesheet" href="{% static 'user_profile/css/user_proffile.css' %}" >
    {% endblock style %}
</head>
<body>
    <div1>
    <div class="profile">
        <div class="profile-header">
            <h2>Профиль пользователя</h2>
            <form action="{% url 'changeprofile' %}">
                {% csrf_token %}
                <button class="pencil-btn" type="submit">
                    <svg style="width: 24px; height: 24px;">
                        <svg width="100%" height="100%" fill="#000000" version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="64px" height="64px" viewBox="0 0 528.899 528.899" xml:space="preserve" stroke="#000000"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round" stroke="#CCCCCC" stroke-width="6.346788"></g><g id="SVGRepo_iconCarrier"> <g> <path d="M328.883,89.125l107.59,107.589l-272.34,272.34L56.604,361.465L328.883,89.125z M518.113,63.177l-47.981-47.981 c-18.543-18.543-48.653-18.543-67.259,0l-45.961,45.961l107.59,107.59l53.611-53.611 C532.495,100.753,532.495,77.559,518.113,63.177z M0.3,512.69c-1.958,8.812,5.998,16.708,14.811,14.565l119.891-29.069 L27.473,390.597L0.3,512.69z"></path> </g> </g></svg>
                    </svg>
                </button>
            </form>
            <form action="{% url 'logout' %}" method="post">
                {% csrf_token %}
                <button type="submit" class="exit">
                    <svg style="width: 24px; height: 24px;">
                        <svg width="100%" height="100%" fill="#000000" height="64px" width="64px" version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 56 56" xml:space="preserve"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round" stroke="#000000" stroke-width="3.3600000000000003"> <g> <path d="M54.424,28.382c0.101-0.244,0.101-0.519,0-0.764c-0.051-0.123-0.125-0.234-0.217-0.327L42.208,15.293 c-0.391-0.391-1.023-0.391-1.414,0s-0.391,1.023,0,1.414L51.087,27H20.501c-0.552,0-1,0.447-1,1s0.448,1,1,1h30.586L40.794,39.293 c-0.391,0.391-0.391,1.023,0,1.414C40.989,40.902,41.245,41,41.501,41s0.512-0.098,0.707-0.293l11.999-11.999 C54.299,28.616,54.373,28.505,54.424,28.382z"></path> <path d="M36.501,33c-0.552,0-1,0.447-1,1v20h-32V2h32v20c0,0.553,0.448,1,1,1s1-0.447,1-1V1c0-0.553-0.448-1-1-1h-34 c-0.552,0-1,0.447-1,1v54c0,0.553,0.448,1,1,1h34c0.552,0,1-0.447,1-1V34C37.501,33.447,37.053,33,36.501,33z"></path> </g> </g><g id="SVGRepo_iconCarrier"> <g> <path d="M54.424,28.382c0.101-0.244,0.101-0.519,0-0.764c-0.051-0.123-0.125-0.234-0.217-0.327L42.208,15.293 c-0.391-0.391-1.023-0.391-1.414,0s-0.391,1.023,0,1.414L51.087,27H20.501c-0.552,0-1,0.447-1,1s0.448,1,1,1h30.586L40.794,39.293 c-0.391,0.391-0.391,1.023,0,1.414C40.989,40.902,41.245,41,41.501,41s0.512-0.098,0.707-0.293l11.999-11.999 C54.299,28.616,54.373,28.505,54.424,28.382z"></path> <path d="M36.501,33c-0.552,0-1,0.447-1,1v20h-32V2h32v20c0,0.553,0.448,1,1,1s1-0.447,1-1V1c0-0.553-0.448-1-1-1h-34 c-0.552,0-1,0.447-1,1v54c0,0.553,0.448,1,1,1h34c0.552,0,1-0.447,1-1V34C37.501,33.447,37.053,33,36.501,33z"></path> </g> </g></svg>
                    </svg>
                </button>
            </form>
        </div>
        
        <img src="{{ about_user.img.url }}" alt="{{ announ.name }}" class="owner_profile-image">
        <p><strong>Имя:</strong> {{ about_user.name }}</p>
        <p><strong>Фамилия:</strong> {{ about_user.surname }}</p>
        <p><strong>Email:</strong> {{ email }}</p>
        <p><strong>Немного обо мне:</strong> {{ about_user.bio }}</p>
        <p><strong>Адрес:</strong> {{ about_user.location }}</p>
        <p><strong>Дата рождения:</strong> {{ about_user.birth_date }}</p>
        <!-- Добавьте дополнительные поля здесь, если необходимо -->
        <a href="{% url 'pass_reset' %}" class="btn btn-dark">Поменять пароль</a>
    </div>
</div1>
    <!-- Раздел для объявлений пользователя -->
<div2>
    <div class="user-ads">
        <h3>Объявления пользователя</h3>
        {% for announ in announs %}
        <div class="announ-container">
            <img src="{{ announ.img.url }}" alt="Фото объявления" class="announ-image">
            <div class="announ-details">
                <!-- Добавляем подпись к названию -->
                <h2><a href="{% url 'announshow' announ.id_announ %}">{{ announ.name }}</a></h2>
                <p>Стоимость: <span class="announ-value">{{ announ.value }}</span> руб.</p>
                <p>Категория: <span class="announ-cat">{{ announ.announ_cat }}</span></p>
                <!-- Добавляем подпись к изображению -->
                <p class="announ-description">{{ announ.description }}</p>
            </div>
        </div>
        {% endfor %}
    </div>
</div2>

    
    
</body>
</html>
{% endblock content %}