announproject/urls.py

from django.contrib import admin
from announ import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from user_profile import prof_views
from chat import chat_views

from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.main, name='home'),
    path('SRAST/', views.SRAST, name='SRAST'),
    path('SRAST/createannoun/',views.announcreate,name='announcreate'),
    path('SRAST/announs/id=<int:id>',views.announshow,name='announshow'),
    path('SRAST/announs/', views.allannoun, name='announlist'),
    path('SRAST/profile/', prof_views.user_profile, name='user_profile'),
     path('SRAST/profile/change', prof_views.change_profile, name='changeprofile'),
    path('SRAST/category/<int:category_id>/', views.category_detail, name='category'),
    path('SRAST/announs/id=<int:id>/profile',prof_views.owner_profile,name='owner_profile'),
    path('accounts/', include('registration.urls')),
     path('SRAST/inbox/', chat_views.inbox, name="inbox"),
    path('SRAST/message/<str:pk>/', chat_views.viewMessage, name="message"),
    path('SRAST/create-message/<int:user_id>/', chat_views.createMessage, name="create-message"),
   # path('', TemplateView.as_view(template_name="index.html"), name='home'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

announ/models.py

# Create your models here.

announ/forms.py
from django import forms
from our_models import views
from django.conf import settings

class announForm(forms.Form):
    about = forms.CharField(label="Описание")
    name = forms.CharField(label="Назвние объявления")
    img = forms.ImageField(label="Изображение")
    value = forms.IntegerField(label="Цена за услугу",initial=settings.MEDIA_URL + 'images/default.png', required=False)
    cat = forms.ModelChoiceField(queryset=views.Cat_get_all(), label="Категория")



announ/views.py
import uuid
from django.shortcuts import redirect, render
from django.http import HttpResponse, HttpResponseRedirect
from announproject.settings import EMAIL_HOST_USER
from .forms import announForm
from user_profile.forms import ProfileForm
from our_models import views
import os
from django.conf import settings
from django.urls import reverse
from django.contrib.auth.decorators import login_required

def main(request):
    return HttpResponseRedirect("/SRAST")

def SRAST(request):
    announcements = views.Announmodel_Get_All()
    categories = views.Cat_get_all()
    return render(request, 'SRAST.html', {'announcements': announcements, 'categories': categories})

@login_required
def announcreate(request):
    profile = views.Get_Profile_by_user(request.user)
    if profile.is_verified:
        if request.method == "POST":
            # Получение данных из запроса
            am=views.Create_AnnounModel()
            am.name = request.POST.get('name')
            am.about=request.POST.get('about')
            am.img = request.FILES.get('img')
            am.value = request.POST.get('value')
            am.announ_cat = views.Cat_get(request.POST.get('cat'))
            #загоняем данные в модель для сохранения в бд
            #нужно прикрутить получение айди юзера
            am.id_account = views.Get_Profile_by_user(request.user)
            views.Save_in_bd(am)

            return HttpResponseRedirect(reverse('announshow', args=(am.id_announ,)))
        else:
            uf = announForm()
            return render(request, "announ/announcreate.html", {"form": uf})
    else:
        return render(request,'announ/atemption.html')
    
def announshow(request,id):
    an = views.Get_object_or_404_Announmodel(id)
    pathtoimg = settings.MEDIA_URL + str(an.img)
    related_announs = views.Announmodel_Get_All().filter(announ_cat=an.announ_cat).exclude(id_announ=an.id_announ)
    user_about = an.id_account
    return render(request,"announ/announshow.html",{"announ":an,"related_announs1":related_announs[0:2],"related_announs2":related_announs[2:4], "user_about":user_about})


def allannoun(request):
     # Получаем все объекты модели AnnounModel
    announs = views.Announmodel_Get_All()
    return render(request, 'announ/allannoun.html',  {'announs': announs})


def category_detail (request, category_id):
    announs = views.Announmodel_Get_All().filter(announ_cat__id = category_id)
    category = views.Cat_get(category_id)
    announ_count = announs.count()
    return render(request, 'announ/category_detail.html', {'announs': announs, 'category': category, 'announ_count':announ_count})


announ/templates/announ/allannoun.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Список объявлений
{% endblock title %}

{% block style %}
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'announ/css/allannoun.css' %}" >
{% endblock style %}


{% block content %}
{% for announ in announs %}
        <div class="announ-container">
            <img src="{{ announ.img.url }}" alt="Фото объявления" class="announ-image">
            <div class="announ-details">
                <!-- Добавляем подпись к названию -->
                <h2><a href="{% url 'announshow' announ.id_announ %}">{{ announ.name }}</a></h2>
                <p>Стоимость: <span class="announ-value">{{ announ.value }}</span> руб.</p> <!-- Добавляем единицу измерения к цене -->
                <p>Категория: <span class="announ-cat">{{ announ.announ_cat }}</span></p>
                <!-- Добавляем подпись к изображению -->
                <p class="announ-description">{{ announ.description }}</p>
            </div>
        </div>
    {% endfor %}
    <div style="justify-content: center; display: flex; align-items: center; margin-top: 30px;">
        <a href="{% url 'announcreate'%}" class="createbtn">+</a>
    </div>
{% endblock content %}

announ/templates/announ/announcreate.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Создание объявления
{% endblock title %}

{% block style %}
<link rel="stylesheet" href="{% static 'announ/css/announcreate.css' %}" >
{% endblock style %}


{% block content %}
<div class="form-container">
    <form method="POST" enctype="multipart/form-data">
     {% csrf_token %}
     <div class="form-field">
         <label for="id_name">Название объявления</label>
         {{ form.name }}
     </div>
     <div class="form-field">
         <label for="id_about">Описание</label>
         {{ form.about }}
     </div>
     <div class="form-field">
         <label for="id_img">Изображение</label>
         {{ form.img }}
     </div>
     <div class="form-field">
         <label for="id_value">Цена за услугу</label>
         {{ form.value }}
     </div>
     <div class="form-field">
         <label for="id_cat">Категория</label>
         {{ form.cat }}
     </div>
     <input type="submit" value="Отправить">
    </form>
</div>
{% endblock content %}

announ/templates/announ/announshow.html
{% extends "base.html" %}
{% load static %}

{% block title %}
{{ announ.name }}
{% endblock title %}

{% block style %}
<link rel="stylesheet" href="{% static 'announ/css/announshow.css' %}" >
{% endblock style %}


{% block content %}
<div1>
<div class="announcement-container">
    <div class="announcement-field announcement-title">{{ announ.name }}</div>
    <img src="{{ announ.img.url }}" alt="{{ announ.name }}" class="announcement-image">
    <div class="announcement-field announcement-description">{{ announ.about }}</div>
    <div class="announcement-field announcement-price">{{ announ.value }} руб.</div>
    <div class="announcement-field announcement-price"><a href = '{% url "owner_profile" announ.id_announ %}'>{{ user_about.surname }} {{ user_about.name }}</a></div>
    {% if request.user.profile.id != user_about.id %}
         <a href="{% url 'create-message' user_about.id %}" class="btn btn--sub btn--lg">Написать сообщение </a>
    {% endif %}
    <div class="announcement-field announcement-category">{{ announ.announ_cat }}</div>
</div>
</div1>
<div2> <div class="related-announcements">
    <h2></h2><br>
    {% for related_announ in related_announs1 %}
        <a href="{% url 'announshow' related_announ.id_announ %}" class="announcement-link">
            <div class="related-announcement-container">
                <div class="announcement-field announcement-title">{{ related_announ.name }}</div>
                <img src="{{ related_announ.img.url }}" alt="{{ related_announ.name }}" class="related-announcement-image">
                <div class="announcement-field announcement-price">{{ related_announ.value }} руб.</div>
            </div>
        </a>
    {% endfor %}
</div>
</div></div2>

<div3> <div class="related-announcements">
    <h2>Похожие объявления:</h2>
    {% for related_announ in related_announs2 %}
        <a href="{% url 'announshow' related_announ.id_announ %}" class="announcement-link">
            <div class="related-announcement-container">
                <div class="announcement-field announcement-title">{{ related_announ.name }}</div>
                <img src="{{ related_announ.img.url }}" alt="{{ related_announ.name }}" class="related-announcement-image">
                <div class="announcement-field announcement-price">{{ related_announ.value }} руб.</div>
            </div>
        </a>
    {% endfor %}
</div>
</div></div3>
{% endblock content %}


announ/templates/announ/atemption.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<h2>Пожалуйста, подтвердите почту</h2>
{% endblock content %}

announ/templates/announ/category_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Профиль
{% endblock title %}

{% block style %}
<link rel="stylesheet" href="{% static 'announ/css/allannoun.css' %}" >
{% endblock style %}


{% block content %}
<div style="padding:0 20px;">
    <h1>{{ category.name }}</h1>
    {% if announ_count == 1 %}
    <h2>Всего одно объявление</h2>
    {% elif announ_count > 1 and announ_count < 5 %}
        <h2>Всего {{announ_count}} объявления</h2>
    {% else %}
        <h2>Всего {{announ_count}} объявлений</h2>
    {% endif %}
</div>
<h1>
{% for announ in announs %}
<div class="announ-container">
    <img src="{{ announ.img.url }}" alt="Фото объявления" class="announ-image">
    <div class="announ-details">
        <!-- Добавляем подпись к названию -->
        <h2><a href="{% url 'announshow' announ.id_announ %}">{{ announ.name }}</a></h2>
        <p>Стоимость: <span class="announ-value">{{ announ.value }}</span> руб.</p> <!-- Добавляем единицу измерения к цене -->
        <p>Категория: <span class="announ-cat">{{ announ.announ_cat }}</span></p>
        <!-- Добавляем подпись к изображению -->
        <p class="announ-description">{{ announ.description }}</p>
    </div>
</div>
{% endfor %}
<div style="text-align: center; margin-top: 30px auto;">
    <a href="{% url 'announcreate'%}" class="createbtn">+</a>
</div>
{% endblock content %}